<?php
/**
 * @file
 * Handles the creation and display of file_storage Islandora objects.
 */

/**
 * Implements hook_theme().
 */
function islandora_file_storage_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_file_storage' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-file-storage',
      'pattern' => 'islandora_file_storage__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_file_storage_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_file_storage');
  $islandora_path = drupal_get_path('module', 'islandora');
  // File Storage Content Model.
  $file_storage_content_model = $connection->repository->constructObject('islandora:file_storageCModel');
  $file_storage_content_model->owner = 'fedoraAdmin';
  $file_storage_content_model->label = 'Islandora File Storage Content Model';
  $file_storage_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $file_storage_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_file_storage_ds_composite_model.xml", FALSE);
  $file_storage_content_model->ingestDatastream($datastream);
  // Image Collection.
  $file_storage_collection = $connection->repository->constructObject('islandora:file_storage_collection');
  $file_storage_collection->owner = 'fedoraAdmin';
  $file_storage_collection->label = 'File Storage Collection';
  $file_storage_collection->models = 'islandora:collectionCModel';
  $file_storage_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $file_storage_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_file_storage_collection_policy.xml", FALSE);
  $file_storage_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $file_storage_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $file_storage_collection->ingestDatastream($datastream);
  return array(
    'islandora_file_storage' => array(
      'title' => 'Islandora File Storage',
      'objects' => array(
        $file_storage_content_model,
        $file_storage_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_file_storage_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_file_storage_mods_form' => array(
      'content_model' => 'islandora:file_storageCModel',
      'form_name' => 'File Storage MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_file_storage_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_file_storage');
  return array(
    'File Storage MODS form' => array(
      'form_file' => "$module_path/xml/islandora_file_storage_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_file_storage_islandora_file_storageCModel_islandora_ingest_steps() {
  return array(
    'islandora_file_storage' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_file_storage_upload_form',
      'module' => 'islandora_file_storage',
      'file' => 'includes/file_storage_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_file_storage_islandora_file_storageCModel_islandora_view_object(AbstractObject $object) {
  $output = theme('islandora_file_storage', array('islandora_object' => $object));
  return array('' => $output);
}

function islandora_file_storage_islandora_file_storageCModel_islandora_derivative() {
  return array(
    array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'TN',
      'weight' => '0',
      'function' => array(
        'islandora_file_storage_create_thumbnail',
      ),
      'file' => drupal_get_path('module', 'islandora_file_storage') . '/includes/derivatives.inc',
    ),
  );
}
